### ISSUE TITLE
Problem during model training

### ISSUE THREAD

**Issue by Krivetochka** [joonaspu/video-game-behavioural-cloning#1]
Hi! I have successfully recorded the data from the game and converted it. But when I started training the model, the following error appeared:
Traceback (most recent call last):
  File "C:\video-game-behavioural-cloning-master\train.py", line 101, in <module>
    gen = Multi process Atari Data Loader(dataloader_args, args.workers)
  File "C:\video-game-behavioural-cloning-master\utils\atari_dataloader.py", line 524, in __init__
    self.shape = loader._get_image(0, 0).shape
  File "C:\video-game-behavioural-cloning-master\utils\atari_dataloader.py", line 184, in _get_image
    traj_name = self.all_trajs[traj]
IndexError: list index out of range
I tried to solve this error on my own, but I'm new to programming and I couldn't do it. 
I hope you will find time to help me)

**Comment by Miffyli** [comment]
Hey, unfortunately we are not actively developing this thing and have not touched the code in a long while, so it is hard to say where the issue is :( . I'd look for help on some other forums with programmers who are willing to help if you are really blocked.
